const words = [
    {
        "id":"15271",
        "english":"кошка",
        "transcription":"[kæt]",
        "russian":"cat",
        "tags":"",
        "tags_json":"[\"\"]"
    },
    {
        "id":"15272",
        "english":"dog",
        "transcription":"[dɒg]",
        "russian":"собака",
        "tags":"",
        "tags_json":"[\"\"]"
    },
    {
        "id":"15274",
        "english":"money",
        "transcription":"[ˈmʌnɪ]",
        "russian":"деньги",
        "tags":"",
        "tags_json":"[\"\"]"
    },
    {
        "id":"15279",
        "english":"orange",
        "transcription":"[orange]",
        "russian":"оранжевый",
        "tags":"оранжевый",
        "tags_json":"[\"u043eu0440u0430u043du0436u0435u0432u044bu0439\"]"
    },
    {
        "id":"15281",
        "english":"lesson",
        "transcription":"[lesson]",
        "russian":"урок",
        "tags":"",
        "tags_json":"[]"
    },
    {
        "id":"15286",
        "english":"test",
        "transcription":"[test]",
        "russian":"тест",
        "tags":"zdsfgh",
        "tags_json":"[\"zdsfgh\"]"
    },
    {
        "id":"15289",
        "english":"cats",
        "transcription":"[cats]",
        "russian":"кошки",
        "tags":"",
        "tags_json":"[]"
    },
    {
        "id":"15291",
        "english":"flower",
        "transcription":"[flower]",
        "russian":"цветок",
        "tags":"",
        "tags_json":"[]"
    },
    {
        "id":"15297",
        "english":"love",
        "transcription":"[lʌv]",
        "russian":"любовь",
        "tags":"",
        "tags_json":"[]"
    },
    {
        "id":"15298",
        "english":"hope",
        "transcription":"[həʊp]",
        "russian":"надежда",
        "tags":"",
        "tags_json":"[]"
    }
]

export default words